baseURL: "https://futurenursing.at"
title: FutureNursing - /dev/urandom for nursing stuff
theme: PaperMod
copyright: '[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)'
enableRobotsTXT: true
enableGitInfo: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: FutureNurse Team
  # author: ["Me", "You"] # multiple authors
  description: /dev/urandom for nursing stuff
  keywords: [Nurse, Healthcare]
  defaultTheme: dark # dark, light
  disableThemeToggle: false
  images: ["/futurenursing.png"]
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowWordCount: true
  ShowToc: true
  ShowRssButtonInSectionTermList: true
  ShowFullTextinRSS: true
  ShowCodeCopyButtons: true

  assets:
    disableHLJS: true
    disableFingerprinting: false
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  label:
    text: "FutureNursing"
    icon: "/futurenursing.png"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: FutureNursing.at
    subtitle: "/dev/urandom for nursing stuff"
    buttons:
      - name: About
        url: about
      - name: Code
        url: code
      - name: Privacy
        url: privacy
#      - name: Donate
#        url: donate

  socialIcons:
    - name: github
      url: "https://github.com/FutureNursing-at"
# soon:    - name: matrix
#      url: ""
#    - name: twitter
#      url: ""
#    - name: reddit
#      url: ""
    - name: email
      url: "mailto:titanz@pm.me"
    - name: rss
      url: /index.xml

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/FutureNursing-at/FutureNursing.at/blob/development/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary"]

#Enabling Search
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

# Enable Chroma
markup:
    highlight:
        style: dracula
        lineNos: false
        noClasses: false
        guessSyntax: true

menu:
  main:
    - identifier: Categories
      name: Categories
      url: /posts/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: Search
      name: Search
      url: /search/
      weight: 30
    - identifier: Resources
      name: Resources
      url: /resources
      weight: 40

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: true
    simple: false
  twitter:
    disable: false
    enableDNT: true
    simple: false
  vimeo:
    disable: false
    enableDNT: true
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true
